### ISSUE TITLE
Incorrect in the text

### ISSUE THREAD

**Issue by danceking** [tranquilitysmile/asrock-b550-phantom-gaming-itx-ax-opencore#2]
‘This EFI use "Above 4g decoding" and "SAM" enabled in BIOS settings’
The 'Sam', in the B550 motherboard BIOS, should be 'Resizable Bar', after many finding information and verification.

**Comment by tranquilitysmile** [comment]
In my version of bios this function named SAM, but you are correct, it 's the same setting
